server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis 配置文件所在路径
  type-aliases-package: com.my.test.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.46.75:3306/db_springcloud?characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 2
      initial-size: 2
      max-total: 5
      max-wait-millis: 200